# Site settings
title: 空鱼
description: 未知「姿态不明的空鱼」

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gizeta.me" # the base hostname & protocol for your site

author:
  fullname: 空鱼
  github: Gizeta
  bitbucket: Gizeta_sf
  telegram: SkyFish_gz
  weibo: gizeta
  twitter: Gizeta_sf
  disqus: gizetablog

google_analytics: 'UA-33119609-2'

# Syntax highlighting
highlightstyle: 'monokai'

# Handling Reading
exclude: ["README.md", "README.html", "CNAME"]

# Build settings
highlighter: null
markdown: kramdown
